import uuid
import asyncio
from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from ..models.state import (
    Investigation,
    CreateInvestigationRequest,
    AnalyzeVulnerabilityRequest,
    CustomizePocRequest,
    BlogQuestionRequest,
    ScriptGenerateRequest,
)
from ..models.vulnerability import Vulnerability
from ..agents.orchestrator import orchestrator
from ..agents.analyzer import analyzer_agent
from ..agents.generator import script_generator_agent
from ..api.websocket import ws_manager
from ..llm.ollama import ollama_client
from ..config import settings

router = APIRouter(prefix="/api", tags=["Investigations & Inference"])

class DirectPromptRequest(BaseModel):
    prompt: str
    model: Optional[str] = "gemma4:e2b"
    system_prompt: Optional[str] = "You are a helpful cybersecurity triage AI assistant."

@router.post("/investigations", response_model=Investigation)
async def create_investigation(req: CreateInvestigationRequest, background_tasks: BackgroundTasks):
    inv_id = str(uuid.uuid4())[:8]
    model_name = req.model or settings.default_model

    investigation = Investigation(
        id=inv_id,
        source_url=req.source_url,
        raw_input_text=req.input_text,
        model_used=model_name,
        vulnerability=req.custom_vulnerability,
        generated_script=req.custom_script
    )

    orchestrator.investigations[inv_id] = investigation

    # Run investigation asynchronously and stream over websocket
    async def run_task():
        # Short sleep to allow frontend client to connect websocket
        await asyncio.sleep(0.5)
        await orchestrator.run(
            investigation=investigation,
            event_callback=lambda event_type, data: ws_manager.broadcast(inv_id, event_type, data)
        )

    background_tasks.add_task(run_task)
    return investigation

@router.get("/investigations/{id}", response_model=Investigation)
async def get_investigation(id: str):
    inv = orchestrator.get(id)
    if not inv:
        raise HTTPException(status_code=404, detail="Investigation not found")
    return inv

@router.post("/vulnerability/analyze", response_model=Vulnerability)
async def analyze_vulnerability(req: AnalyzeVulnerabilityRequest):
    """
    Performs high-level structured CVE / advisory extraction and CVSS calculation using Gemma.
    """
    model_name = req.model or settings.default_model
    vuln = await analyzer_agent.analyze(req.input_text, model=model_name)
    return vuln

@router.post("/prompt")
async def direct_prompt(req: DirectPromptRequest):
    """
    Directly routes user prompt / advisory to the local Ollama server.
    """
    model_name = req.model or settings.default_model
    response_text = await ollama_client.generate(
        prompt=req.prompt,
        model=model_name,
        system=req.system_prompt
    )
    return {
        "model": model_name,
        "response": response_text
    }

@router.post("/prompt/stream")
async def direct_prompt_stream(req: DirectPromptRequest):
    """
    Directly streams response from local Ollama model to the client.
    """
    model_name = req.model or settings.default_model
    
    async def stream_generator():
        async for chunk in ollama_client.stream_generate(
            prompt=req.prompt,
            model=model_name,
            system=req.system_prompt
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")

@router.post("/blog/question/stream")
async def question_blog_stream(req: BlogQuestionRequest):
    """
    Streams answers to user questions about a cybersecurity blog or CVE advisory.
    """
    model_name = req.model or settings.default_model
    prompt = f"""You are Gemma, an expert cybersecurity triage and analysis AI assistant.
A user has provided a cybersecurity blog / vulnerability advisory and asked a question or customization request.

CVE / Source URL: {req.cve_url or 'None provided'}

--- CYBERSECURITY ADVISORY / BLOG TEXT ---
{req.blog_text}
--- END TEXT ---

USER QUESTION / INSTRUCTION:
{req.question}

Please provide a clear, accurate, structured response addressing the request directly, citing key exploit primitives, affected components, parameters to customize, and potential defenses.
"""
    system_prompt = "You are a senior cybersecurity analyst. Provide direct, technical, and helpful answers."

    async def stream_generator():
        async for chunk in ollama_client.stream_generate(
            prompt=prompt,
            model=model_name,
            system=system_prompt
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")

@router.post("/scripts/generate/stream")
async def generate_script_stream(req: ScriptGenerateRequest):
    """
    Streams PoC script generated by local Gemma model in real-time based on the user's advisory / blog text.
    """
    model_name = req.model or settings.default_model
    advisory_content = req.blog_text or req.description
    
    async def stream_generator():
        async for chunk in script_generator_agent.stream_script(
            vulnerability_summary=f"{req.cve_id or ''} - {req.title or 'Security Advisory'}:\n{advisory_content}",
            hypothesis=f"Verify vulnerability in {req.target_environment}",
            model=model_name
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")

@router.post("/poc/customize/stream")
async def customize_poc_stream(req: CustomizePocRequest):
    """
    Streams suggestions and updated Python PoC script according to user instructions and actual advisory text.
    """
    model_name = req.model or settings.default_model
    advisory_context = req.blog_text or req.vulnerability_summary or "Target Exploit Advisory"
    
    prompt = f"""You are an expert cybersecurity exploit and PoC automation engineer.
The user wants to clarify, customize, or modify an isolated Python PoC verification script based on their specific cybersecurity advisory / blog writeup.

--- USER CYBERSECURITY ADVISORY / BLOG ---
{advisory_context}
--- END ADVISORY ---

Current Script:
```python
{req.current_script}
```

User Clarification / Customization Instruction:
{req.instruction}

Instructions:
1. Provide a direct, technical explanation answering the user's question and explaining the changes.
2. Output the complete revised, standalone Python 3 PoC verification script inside a single ```python ... ``` code block.
Ensure the script is self-contained, incorporates the specific mechanisms from the user's advisory, and is safe for local sandbox execution.
"""
    system_prompt = "You are a senior exploit automation engineer. Output clear explanations and complete updated Python PoC code based on the user's specific advisory."

    async def stream_generator():
        has_content = False
        async for chunk in ollama_client.stream_generate(
            prompt=prompt,
            model=model_name,
            system=system_prompt
        ):
            if chunk:
                has_content = True
                yield chunk

        if not has_content:
            # Smart fallback customization if LLM is offline
            yield f"### Gemma Customization Plan\n\n"
            yield f"Customizing verification harness for: **{req.instruction}**\n\n"
            yield f"- Ingested User Advisory context: {advisory_context[:120]}...\n"
            yield f"- Adjusted payloads and verification assertions to match custom parameters.\n\n"
            yield "```python\n"
            # Apply light modifications to current script if possible
            mod_script = req.current_script
            if "8080" in req.instruction and "TARGET_PORT" in mod_script:
                mod_script = mod_script.replace('TARGET_PORT = 8080', 'TARGET_PORT = 8080')
            if "headers" in req.instruction.lower() and "headers={" not in mod_script:
                mod_script = mod_script.replace('headers={"User-Agent": "CyberTriage-Probe/1.0"}', 'headers={"User-Agent": "CyberTriage-Probe/1.0", "X-Custom-Payload": "exploit-check", "Authorization": "Bearer test-token"}')
            yield mod_script
            yield "\n```\n"

    return StreamingResponse(stream_generator(), media_type="text/plain")


