import uuid
import asyncio
from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from ..models.state import (
    Investigation,
    CreateInvestigationRequest,
    BlogQuestionRequest,
    ScriptGenerateRequest,
)
from ..agents.orchestrator import orchestrator
from ..agents.generator import script_generator_agent
from ..api.websocket import ws_manager
from ..llm.ollama import ollama_client
from ..config import settings

router = APIRouter(prefix="/api", tags=["Investigations & Inference"])

class DirectPromptRequest(BaseModel):
    prompt: str
    model: Optional[str] = "gemma4:e2b"
    system_prompt: Optional[str] = "You are a helpful cybersecurity triage AI assistant."

@router.post("/investigations", response_model=Investigation)
async def create_investigation(req: CreateInvestigationRequest, background_tasks: BackgroundTasks):
    inv_id = str(uuid.uuid4())[:8]
    model_name = req.model or settings.default_model

    investigation = Investigation(
        id=inv_id,
        source_url=req.source_url,
        raw_input_text=req.input_text,
        model_used=model_name
    )

    orchestrator.investigations[inv_id] = investigation

    # Run investigation asynchronously and stream over websocket
    async def run_task():
        # Short sleep to allow frontend client to connect websocket
        await asyncio.sleep(0.5)
        await orchestrator.run(
            investigation=investigation,
            event_callback=lambda event_type, data: ws_manager.broadcast(inv_id, event_type, data)
        )

    background_tasks.add_task(run_task)
    return investigation

@router.get("/investigations/{id}", response_model=Investigation)
async def get_investigation(id: str):
    inv = orchestrator.get(id)
    if not inv:
        raise HTTPException(status_code=404, detail="Investigation not found")
    return inv

@router.post("/prompt")
async def direct_prompt(req: DirectPromptRequest):
    """
    Directly routes user prompt / advisory to the local Ollama server.
    """
    model_name = req.model or settings.default_model
    response_text = await ollama_client.generate(
        prompt=req.prompt,
        model=model_name,
        system=req.system_prompt
    )
    return {
        "model": model_name,
        "response": response_text
    }

@router.post("/prompt/stream")
async def direct_prompt_stream(req: DirectPromptRequest):
    """
    Directly streams response from local Ollama model to the client.
    """
    model_name = req.model or settings.default_model
    
    async def stream_generator():
        async for chunk in ollama_client.stream_generate(
            prompt=req.prompt,
            model=model_name,
            system=req.system_prompt
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")

@router.post("/blog/question/stream")
async def question_blog_stream(req: BlogQuestionRequest):
    """
    Streams answers to user questions about a cybersecurity blog or CVE advisory.
    """
    model_name = req.model or settings.default_model
    prompt = f"""You are Gemma, an expert cybersecurity triage and analysis AI assistant.
A user has pasted a cybersecurity blog / vulnerability advisory and asked a question.

CVE / Source URL: {req.cve_url or 'None provided'}

--- CYBERSECURITY ADVISORY / BLOG TEXT ---
{req.blog_text}
--- END TEXT ---

USER QUESTION:
{req.question}

Please provide a clear, accurate, and structured response addressing the user's question directly, citing key exploit primitives, affected components, and potential defenses where applicable.
"""
    system_prompt = "You are a senior cybersecurity analyst. Provide direct, technical, and helpful answers."

    async def stream_generator():
        async for chunk in ollama_client.stream_generate(
            prompt=prompt,
            model=model_name,
            system=system_prompt
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")

@router.post("/scripts/generate/stream")
async def generate_script_stream(req: ScriptGenerateRequest):
    """
    Streams PoC script generated by local Gemma model in real-time.
    """
    model_name = req.model or settings.default_model
    
    async def stream_generator():
        async for chunk in script_generator_agent.stream_script(
            vulnerability_summary=f"{req.cve_id or ''} - {req.title or ''}: {req.description}",
            hypothesis=f"Verify vulnerability in {req.target_environment}",
            model=model_name
        ):
            yield chunk

    return StreamingResponse(stream_generator(), media_type="text/plain")
